- pmmlserver/rockcraft.yaml
Add missing JAR to ROCK (it stays in /local/share during build). The jar is needed in order to deploy pmmlserver workload with kserve. 
Steps to test: 
- Build the ROCK 
- Change the [default image](https://github.com/canonical/kserve-operators/blob/main/charms/kserve-controller/src/default-custom-images.json#L12) in kserve-controller
- Deploy kserve-controller with adjusted image
- Run Pmmlserver [workload](https://github.com/canonical/kserve-operators/blob/main/charms/kserve-controller/tests/integration/pmml-server.yaml).
> Add missing jar

- sklearnserver/dummy_pyproject.toml
- sklearnserver/rockcraft.yaml
- sklearnserver/tests/test_rock.py
- sklearnserver/tox.ini
adds a rock for the kserve v0.11 sklearnserver based on [this dockerfile](https://github.com/kserve/kserve/blob/release-0.11/python/sklearn.Dockerfile) and the existing Paddle and pmmlserver rocks
This PR refactors a little compared to the previous rocks like pmmlserver.  The main goals were:
* improve readability (the pmmlserver uses a lot of magic but doesn't explain why/how it works - I've tried to add comments here)
* make the image API interchangable with upstream as much as possible (no need for pythonpath or calling `python3`)
Specifically for the `pythonpath`, the [pmmlserver rock](https://github.com/canonical/kserve-rocks/blob/main/pmmlserver/rockcraft.yaml#L19C1-L20C1) needs to add `/pmmlserver:/kserve` to its service `PYTHONPATH` because poetry by default installs a root …
> add sklearnserver rock

- pmmlserver/dummy_pyproject.toml
- pmmlserver/rockcraft.yaml
- pmmlserver/tests/test_rock.py
- pmmlserver/tox.ini
Use the entrypoint-service to correctly propagate the arguments. 
- Rewrite the ROCK according to this PR https://github.com/canonical/kserve-rocks/pull/23
- Write tests
> Use entrypoint-service and refactor pmmlserver

- paddle/rockcraft.yaml
- paddleserver/dummy_pyproject.toml
- paddleserver/rockcraft.yaml
- paddleserver/tests/test_rock.py
- paddleserver/tox.ini
Steps to test 
```
cd paddle 
rockcraft clean && rockcraft pack --verbosity=trace
sudo skopeo --insecure-policy copy oci-archive:paddle-server_0.11.0_amd64.rock docker-daemon:charmedkubeflow/paddle-server:0.11.0
docker run charmedkubeflow/paddle-server:0.11.0
```
There should be an output with deprecation warnings like this 
```
2024-02-13T09:37:06.255Z [pebble] Started daemon.
2024-02-13T09:37:06.261Z [pebble] POST /v1/services 5.266914ms 202
2024-02-13T09:37:06.261Z [pebble] Started default services with change 1.
2024-02-13T09:37:06.265Z [pebble] Service "paddle-server" starting: python3.10 -m paddleserver [ args ]
2024-02-13T09:37:07.581Z [paddle-server] /usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API …
```
> Add paddle-server ROCK rocraft

- paddleserver/rockcraft.yaml
Fixes #28 
```
gsutil cp -r gs://kfserving-examples/models/paddle/resnet ./sample_model/
tox -e pack
tox -e export-to-docker
docker run -v PATH_TO/sample_model:/mnt/models PADDLESERVER_IMAGE --model_name paddle-resnet50 --model_dir=/mnt/models/resnet --http_port=8080
```
> add libgomp1 to paddleserver rock

- sklearnserver/README.md
- sklearnserver/rockcraft.yaml
closes #35 
Launch the server with:
```
gsutil cp -r gs://kfserving-examples/models/sklearn/1.0/model ./sample_model/
docker run -p 8080:8080 -v $(pwd)/sample_model:/mnt/models sklearnserver:0.11.2 --model_name test_model --model_dir=/mnt/models --http_port=8080
```
Test the server with:
```
cat <<EOF >> iris-input-v2.json
{
"inputs": [
{
"name": "input-0",
"shape": [2, 4],
"datatype": "FP32",
"data": [
[6.8, 2.8, 4.8, 1.4],
[6.0, 3.4, 4.5, 1.6]
]
}
]
}
EOF
curl -v \
-H "Content-Type: application/json" \
-d @./iris-input-v2.json \
localhost:8080/v2/models/test_model/infer
```
> bump sklearnserver rock to 0.11.2

- paddleserver/README.md
- paddleserver/rockcraft.yaml
closes #39 
See instructions in `./paddleserver/README.md`
> bump paddleserver to 0.11.2, add testing instructions

- xgbserver/README.md
- xgbserver/dummy_pyproject.toml
- xgbserver/rockcraft.yaml
- xgbserver/tests/test_rock.py
- xgbserver/tox.ini
Closes #26.
See xgboost/readme.md
> add xgboost server rock and tests

- controller/rockcraft.yaml
- controller/tests/test_rock.py
- controller/tox.ini
> feat: add controller rock (v0.11.2)

- agent/rockcraft.yaml
- agent/tests/test_rock.py
- agent/tox.ini
> feat: add agent rock (v0.11.2)

- paddleserver/rockcraft.yaml
Closes: https://github.com/canonical/kserve-rocks/issues/55
I have compared tags `v0.11.2` and `v0.12.1` for this file https://github.com/kserve/kserve/blob/v0.12.1/python/paddle.Dockerfile
Changes: 
- poetry bump
- removing the /usr/share folder
> Update paddleserver to v0.12.1

- sklearnserver/rockcraft.yaml
Closes: https://github.com/canonical/kserve-rocks/issues/55
I have compared tags `v0.11.2` and `v0.12.1` for this file https://github.com/kserve/kserve/blob/v0.12.1/python/sklearn.Dockerfile
Changes: 
- poetry bump
- removing the /usr/share folder
> Update sklearnserver to v0.12.1

- lgbserver/rockcraft.yaml
Closes: https://github.com/canonical/kserve-rocks/issues/54
I have compared tags `v0.11.2` and `v0.12.1` for this file https://github.com/kserve/kserve/blob/v0.12.1/python/lgb.Dockerfile
Changes: 
- poetry bump
- removing the /usr/share folder
> Update lgbserver v0.12.1

- controller/rockcraft.yaml
Closes: https://github.com/canonical/kserve-rocks/issues/51
I have compared tags `v0.12.1` and `v0.11.2` for [this](https://github.com/kserve/kserve/blob/v0.12.1/Dockerfile) file 
Changes: 
- Go version bump
> Update controller rock v0.12.1

- agent/rockcraft.yaml
Closes: https://github.com/canonical/kserve-rocks/issues/58
I have compared tags `v0.12.1` and `v0.11.2` for [this](https://github.com/kserve/kserve/blob/v0.12.1/agent.Dockerfile) file 
Changes: 
- Go version bump
> Update agent rock v0.12.1

- storage-initializer/rockcraft.yaml
Closes: https://github.com/canonical/kserve-rocks/issues/81
I have compared tags `0.12.1` and `0.13.0` for this file https://github.com/kserve/kserve/blob/v0.13.0/python/storage-initializer.Dockerfile
> Update `storage-initializer` to `v0.13.0`

- paddleserver/rockcraft.yaml
Closes: https://github.com/canonical/kserve-rocks/issues/78
I have compared tags `0.12.1` and `0.13.0` for this file https://github.com/kserve/kserve/blob/v0.13.0/python/paddle.Dockerfile
> Update `paddleserver` for `v0.13.0`

- lgbserver/rockcraft.yaml
Closes: https://github.com/canonical/kserve-rocks/issues/77
I have compared tags `0.12.1` and `0.13.0` for this file https://github.com/kserve/kserve/blob/v0.13.0/python/lgb.Dockerfile
> Update `lgbserver` for `v0.13.0`

- sklearnserver/rockcraft.yaml
Closes: https://github.com/canonical/kserve-rocks/issues/80
I have compared tags `0.12.1` and `0.13.0` for this file https://github.com/kserve/kserve/blob/v0.13.0/python/sklearn.Dockerfile
> Update `sklearnserver` for `v0.13.0`

- artexplainer/dummy_pyproject.toml
- artexplainer/rockcraft.yaml
- artexplainer/tests/test_rock.py
- artexplainer/tox.ini
---
* Add rockcraft.yaml
* Add tests
* Add tox.ini
This is re-open request for #92 .
Logs from tests
---
`juju status` after all tests are passed:
```
Model     Controller          Cloud/Region        Version  SLA          Timestamp
kubeflow  microk8s-localhost  microk8s/localhost  3.6.1    unsupported  09:54:41+02:00
App                      Version                Status   Scale  Charm                    Channel          Rev  Address         Exposed  Message
grafana-agent-k8s        0.40.4                 blocked      1  grafana-agent-k8s        latest/stable     80  10.152.183.195  no       Missing ['grafana-cloud-config']|['logging-consumer'] for logging-provider; ['grafana-cloud-config']|['send-remote-wr...
istio-ingressgateway                            active       1  istio-gateway …
```
> Added `artexplainer` rock and tests

- tensorflow-serving/rockcraft.yaml
- tensorflow-serving/tests/test_rock.py
- tensorflow-serving/tox.ini
---
* Add rockcraft.yaml
* Add tests
* Add tox.ini
Logs from tests
---
`juju status` after all tests are passed:
```
Model     Controller          Cloud/Region        Version  SLA          Timestamp
kubeflow  microk8s-localhost  microk8s/localhost  3.6.1    unsupported  16:43:45Z
App                      Version                Status   Scale  Charm                    Channel          Rev  Address         Exposed  Message
grafana-agent-k8s        0.32.1                 blocked      1  grafana-agent-k8s        latest/stable     45  10.152.183.119  no       grafana-cloud-config: off, logging-consumer: off
istio-ingressgateway                            active       1  istio-gateway            1.16/stable     1005  10.152.183.215  no       
istio-pilot …
```
> Add `tensorflow-serving` rock and tests

- huggingfaceserver/dummy_pyproject.toml
- huggingfaceserver/rockcraft.yaml
- huggingfaceserver/tests/test_rock.py
- huggingfaceserver/tox.ini
---
* Add rockcraft.yaml
* Add tests
* Add tox.ini
This is re-open request for #91.
Logs from tests
---
`juju status` after all tests are passed:
```
Model     Controller          Cloud/Region        Version  SLA          Timestamp
kubeflow  microk8s-localhost  microk8s/localhost  3.6.1    unsupported  00:59:28Z
App                      Version                Status   Scale  Charm                    Channel          Rev  Address         Exposed  Message
grafana-agent-k8s        0.40.4                 blocked      1  grafana-agent-k8s        latest/stable     80  10.152.183.167  no       Missing ['grafana-cloud-config']|['logging-consumer'] for logging-provider; ['grafana-cloud-config']|['send-remote-wr...
istio-ingressgateway                            active       1  istio-gateway …
```
> Added `huggingfaceserver` rock and tests

- agent/rockcraft.yaml
Closes: https://warthogs.atlassian.net/browse/KF-6810
Updates: 
- new version of go
Steps to test 
```
rockcraft clean && rockcraft pack --verbosity=trace --debug
sudo rockcraft.skopeo --insecure-policy copy oci-archive:kserve-agent_0.14.1_amd64.rock docker-daemon:misohu/kserve-agent:0.14.1
docker run <image>
docker exec -ti <container> bash
pebble logs 
2025-02-05T08:08:19.549Z [kserve-agent] required key SERVING_READINESS_PROBE missing value
````
> feat: update `agent` rock to v1.14.1

- controller/rockcraft.yaml
Closes: https://warthogs.atlassian.net/browse/KF-6810
Updates: 
- new version of go
Steps to test 
```
rockcraft clean && rockcraft pack --verbosity=trace --debug
sudo rockcraft.skopeo --insecure-policy copy oci-archive:kserve-controller_0.14.1_amd64.rock docker-daemon:misohu/kserve-controller:0.14.1
docker run <image>
docker exec -ti <container> bash
pebble logs 
025-02-05T08:15:19.059Z [kserve-controller] {"level":"info","ts":"2025-02-05T08:15:19Z","logger":"setup","msg":"Setting up client for manager"}
2025-02-05T08:15:19.059Z [kserve-controller] {"level":"error","ts":"2025-02-05T08:15:19Z","logger":"controller-runtime.client.config","msg":"unable to load in-cluster config","error":"unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be …
```
> feat: update `controller` rock to v1.14.1

- lgbserver/dummy_pyproject.toml
- lgbserver/rockcraft.yaml
- lgbserver/tests/test_rock.py
- lgbserver/tox.ini
Closes https://warthogs.atlassian.net/browse/KF-6812
Tested by following the instructions in https://github.com/canonical/kserve-rocks/tree/main/lgbserver#testing
Output of inference request:
```
curl -v \
-H "Content-Type: application/json" \
-d @./iris-input-v2.json \
localhost:8080/v2/models/test_model/infer
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /v2/models/test_model/infer HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.1.2
> Accept: */*
> Content-Type: application/json
> Content-Length: 178
> 
< HTTP/1.1 200 OK
< date: Mon, 10 Feb 2025 09:54:03 GMT
< server: uvicorn
< content-length: 327
< content-type: application/json
< 
* Connection #0 to host localhost left intact
{"model_name":"test_model","model_version":null,"id":"063a1abb-9 …
```
> chore: update lgbserver rock to 0.14.1

- paddleserver/dummy_pyproject.toml
- paddleserver/rockcraft.yaml
- paddleserver/tests/test_rock.py
- paddleserver/tox.ini
Closes: https://warthogs.atlassian.net/browse/KF-6818
Changes:
- python bump to 3.11 
- I had to use build packages in combination with overlay packages as the default python for 22.04 is 3.10 and it just keeps overriding the build python to 3.10.
Test
```
rockcraft clean && rockcraft pack --verbosity=trace --debug
sudo rockcraft.skopeo --insecure-policy copy oci-archive:paddleserver_0.14.1_amd64.rock docker-daemon:misohu/paddleserver:0.14.1
docker run misohu/paddleserver:0.14.1
docker exec -ti <container> bash
_daemon_@ae1df4026bf8:/$ python --version
Python 3.11.0rc1
_daemon_@ae1df4026bf8:/$ python -m pmmlserver
usage: __main__.py [-h] [--http_port HTTP_PORT] [--grpc_port GRPC_PORT] [--workers WORKERS] [--max_threads MAX_THREADS] [--max_asyncio_workers MAX_ASYNCIO_WORKERS] …
```
> feat: update paddleserver for version 0.14.1

- pmmlserver/dummy_pyproject.toml
- pmmlserver/rockcraft.yaml
- pmmlserver/tests/test_rock.py
- pmmlserver/tox.ini
Closes: https://warthogs.atlassian.net/browse/KF-6820
Changes:
- python bump to 3.11 
- I had to use build packages in combination with overlay packages as the default python for 22.04 is 3.10 and it just keeps overriding the build python to 3.10.
Test
```
rockcraft clean && rockcraft pack --verbosity=trace --debug
sudo rockcraft.skopeo --insecure-policy copy oci-archive:pmmlserver_0.14.1_amd64.rock docker-daemon:misohu/pmmlserver:0.14.1
docker run misohu/pmmlserver:0.14.1
docker exec -ti <container> bash
_daemon_@ae1df4026bf8:/$ python --version
Python 3.11.0rc1
_daemon_@ae1df4026bf8:/$ python -m pmmlserver
usage: __main__.py [-h] [--http_port HTTP_PORT] [--grpc_port GRPC_PORT] [--workers WORKERS] [--max_threads MAX_THREADS] [--max_asyncio_workers MAX_ASYNCIO_WORKERS] [--enable_grpc …
```
> feat: update pmmlserver for version 0.14.1

- sklearnserver/dummy_pyproject.toml
- sklearnserver/rockcraft.yaml
- sklearnserver/tests/test_rock.py
- sklearnserver/tox.ini
This PR updates the `sklearnserver` rock to the version used by kserve `0.14.1`.
Expected output after you pack the rock with `tox -e pack` and run it:
```
docker run --entrypoint bash -it edb02ee75964
_daemon_@b658fcff84b6:/$ python --version
Python 3.11.0rc1
_daemon_@b658fcff84b6:/$ python -m sklearnserver
usage: __main__.py [-h] [--http_port HTTP_PORT] [--grpc_port GRPC_PORT] [--workers WORKERS] [--max_threads MAX_THREADS]
[--max_asyncio_workers MAX_ASYNCIO_WORKERS] [--enable_grpc ENABLE_GRPC] [--enable_docs_url ENABLE_DOCS_URL]
[--enable_latency_logging ENABLE_LATENCY_LOGGING] [--configure_logging CONFIGURE_LOGGING]
[--log_config_file LOG_CONFIG_FILE] [--access_log_format ACCESS_LOG_FORMAT] [--model_name MODEL_NAME]
[--predictor_host PREDICTOR_HOST] [--protocol {v1,v2,grpc-v2}] …
```
> Update rock for sklearnserver

- storage-initializer/dummy_pyproject.toml
- storage-initializer/rockcraft.yaml
- storage-initializer/tests/test_rock.py
- storage-initializer/tox.ini
Closes https://warthogs.atlassian.net/browse/KF-6824
Based on the changes in [the diff upstream](https://github.com/kserve/kserve/compare/v0.13.0...v0.14.1#diff-093f27ebdb3756f94606a7e929190d5665389f7fe45177bf72cedb8bfb030277):
* update python to 3.11 in rockcraft.yaml and update the python range in pyproject.toml
* bump the version to 0.14.1
* update poetry version to 1.8.3
* update the permissions to `/mnt` directory to be writable by the same user running the image (daemon in our case)
Other related changes:
* remove `deadsnakes/ppa` from `package-repositories`, it seems to be no longer needed. Rock builds successfully without it.
* use build packages in combination with overlay packages for python 3.11 as the default python for 22.04 is 3.10 and otherwise it keeps overriding the build …
> chore: update storage-initializer rock to 0.14.1

- torchserve-kfs/rockcraft.yaml
- torchserve-kfs/tests/test_rock.py
- torchserve-kfs/tox.ini
---
* Add rockcraft.yaml
* Add tests
* Add tox.ini
Logs from tests
---
`juju status` after all tests are passed:
```
Model     Controller          Cloud/Region        Version  SLA          Timestamp
kubeflow  microk8s-localhost  microk8s/localhost  3.6.1    unsupported  14:53:23Z
App                      Version                Status   Scale  Charm                    Channel          Rev  Address         Exposed  Message
grafana-agent-k8s        0.32.1                 blocked      1  grafana-agent-k8s        latest/stable     45  10.152.183.218  no       logging-consumer: off, grafana-cloud-config: off
istio-ingressgateway                            active       1  istio-gateway            1.16/stable     1005  10.152.183.106  no       
istio-pilot …
```
> Add `torchserve-kfs` rock and tests

- huggingfaceserver/dummy_pyproject.toml
- huggingfaceserver/rockcraft.yaml
- huggingfaceserver/tox.ini
This PR updates the `huggingface` rock to the 0.14.1 image.
Note that I found the changes to the `cuda` package versions by pulling the upstream docker image and 
```
docker pull kserve/huggingfaceserver:v0.14.1
docker run -it --entrypoint bash <image-id>
dpkg -l | grep cuda
```
> chore: Update huggingface rock to 0.14.1

- lgbserver/rockcraft.yaml
- paddleserver/rockcraft.yaml
Closes https://github.com/canonical/kserve-operators/issues/316
This PR adds as `stage-packages` in `lgbserver` and `paddleserver` the `libgomp1` package, which is needed for actually running the executables
- First, clone, this repository, checkout to this branch, and build the 2 images with `rockcraft pack`
- Push them to a Docker registry that is reachable with `docker tag`, `docker push` (I am using my own account for this)
- `git clone https://github.com/canonical/kserve-operators`
- Edit the file in `charms/kserve-controller/src/default-custom-images.json`, and put the image location that you pushed earlier
- Run the integration tests with `tox -e integration`, and they should pass :)
> Add libgomp1 package in stage packages of {lgbserver, paddleserver}

- controller/rockcraft.yaml
Closes https://github.com/canonical/kserve-operators/issues/328
Updates the KServe Controller to not set `readOnlyRootFilesystem` to `True` when creating the Router Knative Service, for an `InferenceGraph`.
1. Deploy CKF 1.10
2. Follow the instructions [here](https://kserve.github.io/website/master/modelserving/inference_graph/image_pipeline/#deploy-inferencegraph) to create an `InferenceGraph`  
* The notebook doesn't have permissions https://github.com/canonical/kserve-operators/issues/327. You'll need to edit the `kubeflow-kserve-edit` ClusterRole to give permissions for `inferencegraphs`
3. Confirm that the Router deployment in the user namespace has `readOnlyRootFilesystem` for the Router container
* The Router Knative Service gets created after the other InferenceServices are ready …
> controller: Override the readOnlyRootFilesystem for router

- agent/rock-ci-metadata.yaml
Introduce a `rock-ci-metadata.yaml` for rock integration. For full file creation steps, refer to
https://github.com/canonical/pipelines-rocks/issues/200#issuecomment-3112245114.
Closes #127
> feat(agent): Add rock-ci-metadata.yaml

- paddleserver/rock-ci-metadata.yaml
Introduce a `rock-ci-metadata.yaml` for rock integration. For full file creation steps, refer to
https://github.com/canonical/pipelines-rocks/issues/200#issuecomment-3112245114.
Closes #132
> feat(paddleserver): Add rock-ci-metadata.yaml

- router/rockcraft.yaml
- router/tox.ini
Closes #183 
To ensure that the licenses are correctly places in the final OCI image, I packed the rock and used `dive` to inspect the image structure.
> chore: Update `router` rock to `v0.15.2`
